baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'oscardelahoya.net'
theme = 'smol'

[[module.imports]]
path = 'github.com/colorchestra/smol'

# Parameters
[params]
    subtitle = "'IT'S ALMOST ALWAYS NEVER EASY'"
    dateFmt = "01.02.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

# Footer
