baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'oscardelahoya.net'
theme = 'smol'

# Parameters
[params]
    subtitle = "'IT'S ALMOST ALWAYS NEVER EASY'"
    dateFmt = "01.02.2006 15:04"

# Header
[menu]
    [[menu.main]]
        identifier = "info"
        name = "Info"
        url = "/info/"
        weight = 1

    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3



# Footer
